name: ZekeArt
favicon: null
layout_spectrum: 0.2772601449396461
typography_spectrum: 0.4419855789747089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
